version: '3.8'
services:
  flask_app:
    build: .
    container_name: flask_tunis_gp25
    environment:
      DATABASE_URL: ${DATABASE_URL}
      FLASK_ENV: production
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - app_network
    volumes:
      - ./static:/app/static:rw

networks:
  app_network:
    driver: bridge