version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_tunis_gp25
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "1598:5432"
    restart: unless-stopped
    networks:
      - app_network
    command: >
      postgres -c listen_addresses='*'
               -c max_connections=200
               -c shared_buffers=256MB

  flask_app:
    build: .
    container_name: flask_tunis_gp25
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      FLASK_ENV: production
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - app_network
    volumes:
      - .:/app

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
